Add ClearML Logger
explosion/spacy-loggers pull request #12
Opened 2022-10-06 08:43 UTC by thepycoder

Thanks a lot for all the great work you all do :)

This PR is to add a logger for [ClearML](https://github.com/allegroai/clearml).

## Some open questions:

### The PR is only tested on [this sample](https://github.com/explosion/projects/tree/v3/pipelines/tagger_parser_ud) project so far. 
I'm a spaCy newbie, so not sure if I should do more testing :)  I got the tip to clone and adapt [this project](https://github.com/explosion/projects/tree/v3/integrations/wandb) which I'll try to do if I can get the time for it.

### Metrics visualisation
Currently, I've grouped all metrics that are more than 1 layer deep on the same graph in the webUI. The reason being that giving every one of them their own separate graph, makes the UI very full of graphs. Now, there are 2 graphs that are chock-full of metrics, but they do belong near each other and it's easy to filter them within the graph itself. Personally, I think this makes sense, but I'm all for changing it like it is in the other loggers if you prefer it that way :)

Here is a gif of what the result looks like:
![graphs_spacy](https://user-images.githubusercontent.com/11781950/194252554-dbec0582-d1e8-4138-aef4-6a491112a47f.gif)

2022-10-14 14:24 UTC, rmitsch requested changes
@thepycoder Thanks a lot for your contribution, looks good! The setup with ClearML works as in the readme described. Only a few nitpicks from my side. Could you be so kind and also run ` black` on your code?

Once all comments have been addressed I'll wait a few days before my approval - to see if any of the other spaCy maintainers want to review this as well.

2022-10-14 14:24 UTC, rmitsch commented on README.md
> +- Miscellanious info such as time, python version and hardware information
```suggestion
- Miscellaneous info such as time, python version and hardware information
```

2022-10-14 14:24 UTC, rmitsch commented on README.md
> +or the open source [self-hosted server](https://github.com/allegroai/clearml-server). This logger captures all the following information (all visible in the webUI):
```suggestion
or the open source [self-hosted server](https://github.com/allegroai/clearml-server). This logger captures all the following information (all visible in the web UI):
```

2022-10-14 14:24 UTC, rmitsch commented on README.md
> +    - Individual component scores are grouped together on 1 scalar plot, use the webUI to filter.
```suggestion
    - Individual component scores are grouped together on one scalar plot, use the web UI to filter.
```

2022-10-14 14:24 UTC, rmitsch commented on spacy_loggers/clearml.py
> +            "The 'mlflow' library could not be found - did you install it? "
```suggestion
            "The 'clearml' library could not be found - did you install it? "
```

2022-10-14 14:24 UTC, rmitsch commented on spacy_loggers/clearml.py
> +
```suggestion
```

2022-10-14 14:24 UTC, rmitsch commented on spacy_loggers/clearml.py
> +
```suggestion


```

2022-10-17 13:48 UTC, rmitsch approved these changes

2022-10-17 13:50 UTC, thepycoder commented
Hi @rmitsch !

Thank you very much for the review! I just ran black on my changes and committed the result.

I also used the built-in "add suggestion to batch" functionality of github for the first time to accept your suggestions, it aparently resolved all the issues automatically, let me know if that's not what you wanted :) All comments were completely valid though, so no counterpoints on my end.

Let me know if you want me to do anything else!

2022-10-25 13:44 UTC, shadeMe reviewed
Looks good overall! Some minor comments below.

2022-10-25 13:44 UTC, shadeMe commented on README.md
> +- The full spaCy config file contents
```suggestion
- The full spaCy config file contents.
```

2022-10-25 13:44 UTC, shadeMe commented on README.md
> +- Full console output
```suggestion
- Full console output.
```

2022-10-25 13:44 UTC, shadeMe commented on README.md
> +- Miscellaneous info such as time, python version and hardware information
```suggestion
- Miscellaneous info such as time, python version and hardware information.
```

2022-10-25 13:44 UTC, shadeMe commented on README.md
> +    - Individual component scores are grouped together on one scalar plot, use the web UI to filter.
```suggestion
    - Individual component scores are grouped together on one scalar plot (filterable using the web UI).
```

2022-10-25 13:44 UTC, shadeMe commented on README.md
> +Then optionally, depending on the setting below, the following can be captured:
```suggestion
In addition to the above, the following artifacts can also be optionally captured:
```

2022-10-31 09:22 UTC, thepycoder commented on spacy_loggers/clearml.py
> +            task_name=task_name if task_name else "spaCy Training",
Sure!

2022-10-31 09:26 UTC, thepycoder commented on spacy_loggers/clearml.py
> +                task.get_logger().report_scalar(
You're right. I also think indexing the dict directly was bad as well. I don't quite know what can and cannot be in the info dict, but it seems safer to use `.get()` instead, so I added that change as well.

2022-10-31 09:51 UTC, thepycoder commented on spacy_loggers/clearml.py
> +            task_name=task_name if task_name else "spaCy Training",
Made it non-optional in both the function argument list and updated the readme as well.

2022-10-31 09:56 UTC, thepycoder commented
@shadeMe Thank you so much for the PR review.

First, I apologize, the code is ok, but it seems I was very sloppy with the docs in leaving e.g. MLFlow references in there. That should not have been on you guys to find!

Next, I implemented your suggestions, please check 2 of them that I left comments on.

Please Note: I also added an additional commit that changes the output dataset ID. It was an HTML link before, but it did not actually parse correctly on our end! So I'm reverting back to just the ID.

Thanks again for the work you guys put in here!

2022-10-31 10:17 UTC, shadeMe approved these changes

2022-10-31 10:25 UTC, merged

2022-10-31 10:25 UTC, rmitsch commented
Merged :tada: Thanks again, @thepycoder! And thanks to @shadeMe for doing a more thorough review than me :pray: